config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
  resources :reviews, only: [:new, :create, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: ['chinese', 'italian', 'japanese', 'french', 'belgian']}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :restaurant_id, presence: true
  validates :rating, numericality: true, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5] }
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def show
    @review = Review.find(params[:id])
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <header class="bg-light mb-5 px-4 py-3 border-bottom d-flex sticky-top justify-content-between align-items-center">
      <%= link_to "Restaurants", restaurants_path, class: 'm-0 text-muted h4 text-decoration-none' %>
      <%= link_to "Create Restaurant", new_restaurant_path, class: 'btn btn-primary m-0' %>
    </header>
    <%= yield %>
    <footer class="bg-dark mt-5 p-5 text-center">
      <p class="text-white m-0">Made in London @ Le Wagon</p>
    </footer>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :category %>
  </div>

  <div class="form-actions btn btn-primary" >
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/index.html.erb
<h1> Restaurants </h1>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Category</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
     <% @restaurants.each do |restaurant|  %>
     <tr>
      <td> <%= restaurant.name %> </td>
       <td> <%= restaurant.address %> </td>
      <td>  <%= restaurant.category %> </td>
      <td><%= link_to 'Show', restaurant, class: "btn btn-primary mb-5 px-4 py-3" %></td>
    </tr>
   <% end %>
  </tbody>
 </table>

<%= link_to 'New Restaurant', new_restaurant_path, class: "btn btn-primary" %>

app/views/restaurants/new.html.erb
<h1> New Restaurant </h1>

<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Category:</strong>
  <%= @restaurant.category %>
</p>


<p>
  <strong>Reviews:</strong>
  <% @restaurant.reviews.each do |review| %>
    <li><%= link_to review.content, restaurant_review_path(review) %></li>
  <% end %>
</p>

<%= link_to "New Review", new_restaurant_review_path(@restaurant), class: "btn btn-primary"%>

<%= link_to "Home", restaurants_path, class: "btn btn-primary"%>

app/views/reviews/new.html.erb
<h1>Fill in the review form</h1>
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <%= simple_form_for [@restaurant, @review] do |f| %>
        <%= f.input :content %>
         <%= f.input :rating %>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/show.html.erb
<h1>Review for <%= @review.restaurant.name %>:</h1>
<p><%= @review.content %></p>
<% @review.rating.times do |time| %>
    <i class="fas fa-star"></i>
  <% end %>
  <% (5 - @review.rating).times do |time| %>
    <i class="far fa-star"></i>
  <% end %>